changing the pids limitation on scheduler
opentelekomcloud/ansible-collection-apimon pull request #12
Opened 2024-05-07 15:39 UTC by vladimirhasko

2024-05-07 16:04 UTC, gtema requested changes
let's add reference to the StackOverflow describing that, otherwise it is very hard to understand purpose.

2024-05-08 09:00 UTC, gtema commented
I meant adding reference (as a comment) into the changed systemd unitfile. This will also help knowing the context once looking at the unitfile deployed to system.

2024-05-08 16:57 UTC, vladimirhasko commented
> I meant adding reference (as a comment) into the changed systemd unitfile. This will also help knowing the context once looking at the unitfile deployed to system.

I knew :) I just wanted to fix the UTF-8 issue first

2024-05-08 17:02 UTC, gtema approved these changes

2024-05-08 17:15 UTC, merged